//! Protocol type contract generator.
//!
//! Emits a TypeScript declaration file describing the JSON shape of
//! key `desktop-core` types so the frontend can import a single
//! source of truth instead of hand-maintaining matching `interface`
//! declarations in `apps/desktop-shell/src/lib/tauri.ts`.
//!
//! ── Approach ────────────────────────────────────────────────────
//!
//! Rather than introducing a heavy proc-macro dependency like `ts-rs`
//! or `schemars`, we build sample instances of each type, serialize
//! them with serde, and walk the resulting JSON value to emit a
//! corresponding TypeScript interface. This is a *reflection-based*
//! approach: the output mirrors whatever serde produces, so it's
//! always in sync with the actual wire format.
//!
//! Limitations:
//! - Optional fields are inferred from `null` in the sample (the
//!   sample must use `None`/`null` for fields that should be `?:`).
//! - Enum tags use the `#[serde(tag, rename_all)]` set on each enum.
//! - Nested objects are inlined; we don't deduplicate shared types.
//!
//! Generated file: `apps/desktop-shell/src/lib/protocol.generated.ts`
//!
//! Run via:
//!   cargo test -p desktop-core protocol_codegen -- --ignored --nocapture

use serde_json::Value;
use std::fmt::Write as _;

/// Walk a JSON value and emit a TypeScript type expression.
pub fn json_to_ts(value: &Value, indent: usize) -> String {
    match value {
        Value::Null => "null".to_string(),
        Value::Bool(_) => "boolean".to_string(),
        Value::Number(_) => "number".to_string(),
        Value::String(_) => "string".to_string(),
        Value::Array(arr) => {
            if arr.is_empty() {
                "unknown[]".to_string()
            } else {
                format!("Array<{}>", json_to_ts(&arr[0], indent))
            }
        }
        Value::Object(map) => {
            let pad = "  ".repeat(indent + 1);
            let close = "  ".repeat(indent);
            let mut out = String::from("{\n");
            for (k, v) in map {
                let _ = write!(
                    out,
                    "{pad}{}: {};\n",
                    quote_key(k),
                    json_to_ts(v, indent + 1)
                );
            }
            out.push_str(&close);
            out.push('}');
            out
        }
    }
}

fn quote_key(key: &str) -> String {
    let needs_quote = key.chars().any(|c| !c.is_alphanumeric() && c != '_');
    if needs_quote {
        format!("\"{key}\"")
    } else {
        key.to_string()
    }
}

/// Build a TypeScript declaration block for a single named type.
pub fn ts_interface(name: &str, sample: &Value) -> String {
    let body = json_to_ts(sample, 0);
    format!("export type {name} = {body};\n")
}

/// Build a TypeScript file from (name, sample) pairs.
pub fn ts_file(types: &[(&str, Value)]) -> String {
    let mut out = String::from(
        "// AUTO-GENERATED by desktop-core::protocol_codegen — do not edit by hand.\n\
         // Run `cargo test -p desktop-core protocol_codegen -- --ignored --nocapture`\n\
         // to regenerate from the Rust types.\n\
         //\n\
         // The shapes below are produced by serializing sample instances of\n\
         // each Rust type and walking the resulting JSON. They may be slightly\n\
         // looser than the Rust definitions (e.g. number vs u64) but reflect\n\
         // exactly what the HTTP API emits over the wire.\n\n",
    );
    for (name, sample) in types {
        out.push_str(&ts_interface(name, sample));
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        DesktopLifecycleStatus, DesktopSessionBucket, DesktopSessionDetail,
        DesktopSessionData, DesktopSessionSummary, DesktopTurnState,
    };

    fn sample_summary() -> DesktopSessionSummary {
        DesktopSessionSummary {
            id: "desktop-session-1".into(),
            title: "Sample".into(),
            preview: "preview text".into(),
            bucket: DesktopSessionBucket::Today,
            created_at: 1_700_000_000_000,
            updated_at: 1_700_000_001_000,
            project_name: "demo".into(),
            project_path: "/tmp/demo".into(),
            environment_label: "Local".into(),
            model_label: "Opus 4.6".into(),
            turn_state: DesktopTurnState::Idle,
            lifecycle_status: DesktopLifecycleStatus::Todo,
            flagged: false,
        }
    }

    fn sample_detail() -> DesktopSessionDetail {
        DesktopSessionDetail {
            id: "desktop-session-1".into(),
            title: "Sample".into(),
            preview: "preview text".into(),
            created_at: 1_700_000_000_000,
            updated_at: 1_700_000_001_000,
            project_name: "demo".into(),
            project_path: "/tmp/demo".into(),
            environment_label: "Local".into(),
            model_label: "Opus 4.6".into(),
            turn_state: DesktopTurnState::Idle,
            lifecycle_status: DesktopLifecycleStatus::InProgress,
            flagged: true,
            session: DesktopSessionData {
                version: 1,
                session_id: "session-1".into(),
                created_at_ms: 1_700_000_000_000,
                updated_at_ms: 1_700_000_001_000,
                messages: Vec::new(),
                compaction: None,
                fork: None,
            },
        }
    }

    /// Smoke test: verify json_to_ts handles primitives + objects + arrays.
    #[test]
    fn json_to_ts_primitives() {
        assert_eq!(json_to_ts(&Value::Null, 0), "null");
        assert_eq!(json_to_ts(&serde_json::json!(true), 0), "boolean");
        assert_eq!(json_to_ts(&serde_json::json!(42), 0), "number");
        assert_eq!(json_to_ts(&serde_json::json!("hi"), 0), "string");
        assert_eq!(
            json_to_ts(&serde_json::json!([1, 2, 3]), 0),
            "Array<number>"
        );
    }

    /// Smoke test: object emits a `{ key: type; }` block.
    #[test]
    fn json_to_ts_object() {
        let v = serde_json::json!({"name": "x", "count": 3, "ok": true});
        let ts = json_to_ts(&v, 0);
        assert!(ts.contains("name: string;"));
        assert!(ts.contains("count: number;"));
        assert!(ts.contains("ok: boolean;"));
    }

    /// Smoke test: ts_interface produces a valid `export type` declaration.
    #[test]
    fn ts_interface_wraps_with_export_type() {
        let value = serde_json::json!({"id": "abc", "count": 1});
        let result = ts_interface("Sample", &value);
        assert!(result.starts_with("export type Sample = {"));
        assert!(result.contains("id: string;"));
        assert!(result.contains("count: number;"));
    }

    /// Generate the contract file. Marked `#[ignore]` so it doesn't run
    /// on every `cargo test`. Invoke explicitly to regenerate.
    #[test]
    #[ignore]
    fn generate_protocol_types_file() {
        let types: Vec<(&str, Value)> = vec![
            (
                "GeneratedSessionSummary",
                serde_json::to_value(sample_summary()).unwrap(),
            ),
            (
                "GeneratedSessionDetail",
                serde_json::to_value(sample_detail()).unwrap(),
            ),
            (
                "GeneratedLifecycleStatus",
                serde_json::to_value(DesktopLifecycleStatus::NeedsReview).unwrap(),
            ),
            (
                "GeneratedTurnState",
                serde_json::to_value(DesktopTurnState::Running).unwrap(),
            ),
        ];

        let file_contents = ts_file(&types);

        // Locate the frontend src/lib/ directory relative to CARGO_MANIFEST_DIR.
        // Manifest is .../rust/crates/desktop-core, so we walk up 3 to reach
        // the workspace root, then into apps/desktop-shell/src/lib.
        let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set");
        let workspace_root = std::path::Path::new(&manifest)
            .ancestors()
            .nth(3) // desktop-core → crates → rust → workspace root
            .unwrap();
        let target = workspace_root
            .join("apps")
            .join("desktop-shell")
            .join("src")
            .join("lib")
            .join("protocol.generated.ts");

        eprintln!("workspace_root = {}", workspace_root.display());
        eprintln!("target = {}", target.display());
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent).expect("create lib dir");
        }
        std::fs::write(&target, file_contents).expect("write generated TS file");
        println!("✓ wrote {}", target.display());
    }

    /// Sanity test: the sample types serialize and round-trip through
    /// json_to_ts without panicking.
    #[test]
    fn samples_round_trip_through_codegen() {
        for (_name, sample) in [
            ("Summary", serde_json::to_value(sample_summary()).unwrap()),
            ("Detail", serde_json::to_value(sample_detail()).unwrap()),
        ] {
            let ts = json_to_ts(&sample, 0);
            assert!(ts.starts_with("{"));
            assert!(ts.contains("id: string;"));
        }
    }
}
