// AUTO-GENERATED by desktop-core::protocol_codegen — do not edit by hand.
// Run `cargo test -p desktop-core protocol_codegen -- --ignored --nocapture`
// to regenerate from the Rust types.
//
// The shapes below are produced by serializing sample instances of
// each Rust type and walking the resulting JSON. They may be slightly
// looser than the Rust definitions (e.g. number vs u64) but reflect
// exactly what the HTTP API emits over the wire.

export type GeneratedSessionSummary = {
  bucket: string;
  created_at: number;
  environment_label: string;
  flagged: boolean;
  id: string;
  lifecycle_status: string;
  model_label: string;
  preview: string;
  project_name: string;
  project_path: string;
  title: string;
  turn_state: string;
  updated_at: number;
};

export type GeneratedSessionDetail = {
  created_at: number;
  environment_label: string;
  flagged: boolean;
  id: string;
  lifecycle_status: string;
  model_label: string;
  preview: string;
  project_name: string;
  project_path: string;
  session: {
    compaction: null;
    created_at_ms: number;
    fork: null;
    messages: unknown[];
    session_id: string;
    updated_at_ms: number;
    version: number;
  };
  title: string;
  turn_state: string;
  updated_at: number;
};

export type GeneratedLifecycleStatus = string;

export type GeneratedTurnState = string;

