// AUTO-GENERATED by desktop-core::protocol_codegen — do not edit by hand.
// Run `cargo test -p desktop-core protocol_codegen -- --ignored --nocapture`
// to regenerate from the Rust types.
//
// The shapes below are produced by serializing sample instances of
// each Rust type and walking the resulting JSON. They may be slightly
// looser than the Rust definitions (e.g. number vs u64) but reflect
// exactly what the HTTP API emits over the wire.

export type GeneratedSessionSummary = {
  bucket: string;
  created_at: number;
  environment_label: string;
  flagged: boolean;
  id: string;
  lifecycle_status: string;
  model_label: string;
  preview: string;
  project_name: string;
  project_path: string;
  title: string;
  turn_state: string;
  updated_at: number;
};

export type GeneratedSessionDetail = {
  context_basis: {
    auto_bound: boolean;
    bound_source: {
      id: number;
      kind: string;
      title: string;
    };
    boundary_marker: boolean;
    grounding_applied: boolean;
    history_turns_included: number;
    mode: string;
    source_included: boolean;
    source_token_hint: number;
  };
  created_at: number;
  enrich_status: {
    kind: string;
    raw_id: number;
    title: string;
  };
  environment_label: string;
  flagged: boolean;
  id: string;
  lifecycle_status: string;
  model_label: string;
  preview: string;
  project_name: string;
  project_path: string;
  session: {
    compaction: null;
    created_at_ms: number;
    fork: null;
    messages: unknown[];
    session_id: string;
    updated_at_ms: number;
    version: number;
  };
  source_binding: {
    binding_reason: string;
    bound_at: number;
    source: {
      id: number;
      kind: string;
      title: string;
    };
  };
  title: string;
  turn_state: string;
  updated_at: number;
};

export type GeneratedLifecycleStatus = string;

export type GeneratedTurnState = string;

export type GeneratedEnrichStatusSuccess = {
  kind: string;
  raw_id: number;
  title: string;
};

export type GeneratedEnrichStatusRejected = {
  kind: string;
  reason: string;
};

export type GeneratedEnrichStatusPrereq = {
  dep: string;
  hint: string;
  kind: string;
};

export type GeneratedContextBasis = {
  auto_bound: boolean;
  bound_source: {
    id: number;
    kind: string;
    title: string;
  };
  boundary_marker: boolean;
  grounding_applied: boolean;
  history_turns_included: number;
  mode: string;
  source_included: boolean;
  source_token_hint: number;
};

export type GeneratedContextModeFollowUp = string;

export type GeneratedContextModeSourceFirst = string;

export type GeneratedContextModeCombine = string;

export type GeneratedSourceRefRaw = {
  id: number;
  kind: string;
  title: string;
};

export type GeneratedSourceRefWiki = {
  kind: string;
  slug: string;
  title: string;
};

export type GeneratedSourceRefInbox = {
  id: number;
  kind: string;
  title: string;
};

export type GeneratedSessionSourceBinding = {
  binding_reason: string;
  bound_at: number;
  source: {
    id: number;
    kind: string;
    title: string;
  };
};

export type GeneratedBatchResolveInboxRequest = {
  action: string;
  ids: Array<number>;
  reason: string;
};

export type GeneratedBatchFailedItem = {
  error: string;
  id: number;
};

export type GeneratedBatchResolveInboxResponse = {
  failed: Array<{
    error: string;
    id: number;
  }>;
  processed: number;
  success: Array<number>;
  total: number;
};

