/**
 * M5 sprint — pure derivation helpers for the `WeChat Bridge` health UI.
 *
 * `deriveHealth` maps a raw `WeChatChannelHealth` snapshot to one of five
 * stable buckets that `BridgeHealthHeader` / `HealthStatusBadge` use to
 * pick the R1 primitive (Badge vs EmptyState vs FailureBanner). Keeping
 * the logic here means the rules are testable in isolation and the
 * component tree stays presentational.
 *
 * The 5-state contract (see M5 spec):
 *
 *   - `error`         → channel not running AND has last_error
 *   - `disconnected`  → channel not running (no error)
 *   - `degraded`      → running but consecutive_failures >= 3
 *   - `idle`          → running but last inbound message > 30 min ago
 *   - `active`        → running and recent traffic
 *
 * `formatRelativeTime` is a tiny 中文 relative formatter — R1 primitives
 * don't ship one, so the WeChat surface owns it locally. Non-localized by
 * design since the rest of the page uses raw Chinese copy.
 *
 * Types + API wrappers live in `@/lib/tauri` (generated by Worker A from
 * the Rust contract). This module re-exports them under M5-local names
 * for continuity so existing component imports keep compiling.
 */

import {
  fetchWeChatBridgeHealth,
  fetchWeChatIngestConfig,
  updateWeChatIngestConfig,
  type WeChatBridgeHealthResponse,
  type WeChatChannelHealth,
  type WeChatIngestConfig,
} from "@/lib/tauri";

/** M5-local alias preserved for older call sites; canonical name is
 *  `WeChatChannelHealth` on `@/lib/tauri`. */
export type ChannelHealthLike = WeChatChannelHealth;

/** M5-local alias preserved for older call sites; canonical name is
 *  `WeChatBridgeHealthResponse` on `@/lib/tauri`. */
export type BridgeHealthResponse = WeChatBridgeHealthResponse;

export type { WeChatIngestConfig };

export {
  fetchWeChatBridgeHealth,
  fetchWeChatIngestConfig,
  updateWeChatIngestConfig,
};

export type BridgeHealth =
  | "active"
  | "idle"
  | "degraded"
  | "disconnected"
  | "error";

const IDLE_THRESHOLD_MS = 30 * 60 * 1000;
const DEGRADED_FAILURE_THRESHOLD = 3;

/**
 * Given a single-channel snapshot, return the 5-state bucket.
 *
 * Ordering matters: an errored-not-running channel should read as `error`,
 * not `disconnected`, so the user sees the technical detail banner instead
 * of a "桥已断开 → 重连" CTA that likely won't help.
 */
export function deriveHealth(
  channel: ChannelHealthLike,
  nowMs: number = Date.now(),
): BridgeHealth {
  if (!channel.running && channel.last_error) return "error";
  if (!channel.running) return "disconnected";
  if (channel.consecutive_failures >= DEGRADED_FAILURE_THRESHOLD) {
    return "degraded";
  }
  if (
    channel.last_inbound_unix_ms !== null &&
    nowMs - channel.last_inbound_unix_ms > IDLE_THRESHOLD_MS
  ) {
    return "idle";
  }
  return "active";
}

/**
 * Render a unix-ms timestamp as a 中文 relative time string. `null` is
 * treated as "从未" so the header never shows a bare dash.
 */
export function formatRelativeTime(
  unixMs: number | null,
  nowMs: number = Date.now(),
): string {
  if (unixMs === null) return "从未";
  const delta = nowMs - unixMs;
  if (delta < 0) return "刚刚";
  if (delta < 60_000) return "刚刚";
  if (delta < 60 * 60_000) return `${Math.floor(delta / 60_000)} 分钟前`;
  if (delta < 24 * 60 * 60_000) {
    return `${Math.floor(delta / 60 / 60_000)} 小时前`;
  }
  return `${Math.floor(delta / 24 / 60 / 60_000)} 天前`;
}

/** Human-readable channel label for the header. Kept here so the mapping
 *  lives next to the derivation and stays discoverable. */
export function channelLabel(channel: "ilink" | "kefu"): string {
  return channel === "ilink" ? "个微 iLink" : "微信客服";
}
